export const ROLES=
{   ADMIN:"admin",
    MANEGER:"maneger",
    USER:"user",
    Guest:"guest"}
;
export const PERMESSIONS={
    VIEW_DASHBOARD:"view_dashboard",
    VIEW_PRODUCTS:"view_products",
    EDIT_PRODUCTS:"edit_products",
    DELETE_PRODUCTS:"delete_products",
    VIEW_PRODUCT:"view_product"
};
export const ROLES_PERMESSIONS:Record<string,string[]>={
    [ROLES.ADMIN]:[ PERMESSIONS.VIEW_DASHBOARD,PERMESSIONS.DELETE_PRODUCTS,PERMESSIONS.EDIT_PRODUCTS,PERMESSIONS.VIEW_PRODUCT,PERMESSIONS.VIEW_PRODUCTS],
    [ROLES.MANEGER]:[PERMESSIONS.VIEW_PRODUCTS,PERMESSIONS.EDIT_PRODUCTS,PERMESSIONS.DELETE_PRODUCTS],
    [ROLES.USER]:[PERMESSIONS.VIEW_PRODUCTS],
    [ROLES.Guest]:[PERMESSIONS.VIEW_PRODUCTS]
}